spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.qqvucznblwtjrduahhft
spring.datasource.password=+MV!?mdhgwwT-3U
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trenit.verify@gmail.com
spring.mail.password=tovd pzqr jtpq kixv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=9c6c7c4c6a6e8b8ae5g6hf4b7c5a3d1f9c6c7c4c6a6e8b8a2e1d9fgg25la3d1f
jwt.expiration=900000

server.address=0.0.0.0